# Generated by Django 4.0.3 on 2023-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250)),
                ('Age', models.IntegerField()),
                ('statut_vaccial', models.CharField(max_length=250)),
                ('sterillisation', models.CharField(max_length=250)),
            ],
        ),
    ]
