# Generated by Django 4.0.3 on 2023-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250)),
                ('Age', models.IntegerField()),
                ('statut_vaccial', models.CharField(max_length=250)),
                ('sterillisation', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
